### ISSUE TITLE
TreeUI should be accessed only from EDT

### ISSUE THREAD

**Issue by marcelkliemannel** [marcelkliemannel/intellij-jvms-manager-plugin#10]
```java
java.lang.Throwable: TreeUI should be accessed only from EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.ui.tree.ui.DefaultTreeUI.isValid(DefaultTreeUI.java:216)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRowCount(DefaultTreeUI.java:772)
	at java.desktop/javax.swing.JTree.getRowCount(JTree.java:1697)
	at com.intellij.ui.treeStructure.treetable.TreeTableModelAdapter.getRowCount(TreeTableModelAdapter.java:115)
	at java.desktop/javax.swing.JTable.getRowCount(JTable.java:2708)
	at com.intellij.ui.table.JBTable.isEmpty(JBTable.java:391)
	at com.intellij.ui.table.JBTable$1.isStatusVisible(JBTable.java:113)
	at com.intellij.util.ui.StatusText.isStatusVisibleInner(StatusText.java:183)
	at com.intellij.util.ui.StatusText.repaintOwner(StatusText.java:273)
	at com.intellij.util.ui.StatusText.clear(StatusText.java:268)
	at dev.turingcomplete.intellijjvmsmanagerplugin.ui.list.JvmProcessesTable.syncReloadingState(JvmProcessesTable.kt:123)
	at dev.turingcomplete.intellijjvmsmanagerplugin.ui.JvmProcessesMainPanel.collectJvmProcesses(JvmProcessesMainPanel.kt:125)
	at dev.turingcomplete.intellijjvmsmanagerplugin.JvmsManagerPluginService.collectJavaProcesses(JvmsManagerPluginService.kt:26)
	at dev.turingcomplete.intellijjvmsmanagerplugin.ui.action.TerminateProcessesAction$TerminateProcessesTask.onSuccess$lambda$1(TerminateProcessesAction.kt:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by marcelkliemannel** [comment]
Fixed.
