### ISSUE TITLE
Cannot create light service JvmsManagerPluginService because container is already disposed 

### ISSUE THREAD

**Issue by marcelkliemannel** [marcelkliemannel/intellij-jvms-manager-plugin#9]
```java
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service dev.turingcomplete.intellijjvmsmanagerplugin.JvmsManagerPluginService because container is already disposed (container=Project(name=***, containerState=DISPOSE_COMPLETED, componentStore=/Users/marcel.kliemannel/Development/GitLab/service-caa-api) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:752)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:732)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:688)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at dev.turingcomplete.intellijjvmsmanagerplugin.ui.list.JvmProcessesTable._init_$lambda$1(JvmProcessesTable.kt:79)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.addSelectionInterval(DefaultListSelectionModel.java:561)
	at com.intellij.ui.treeStructure.treetable.TreeTable$ListToTreeSelectionModelWrapper.resetRowSelection(TreeTable.java:266)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setRowMapper(DefaultTreeSelectionModel.java:135)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.setSelectionModel(AbstractLayoutCache.java:167)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setSelectionModel(BasicTreeUI.java:647)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.completeUIUninstall(BasicTreeUI.java:1205)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.uninstallUI(BasicTreeUI.java:1178)
	at java.desktop/javax.swing.JComponent.uninstallUIAndProperties(JComponent.java:748)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:721)
	at java.desktop/javax.swing.JTree.setUI(JTree.java:760)
	at com.intellij.ui.treeStructure.Tree.setUI(Tree.java:124)
	at java.desktop/javax.swing.JTree.updateUI(JTree.java:781)
	at com.intellij.ui.treeStructure.treetable.TreeTableTree.updateUI(TreeTableTree.java:44)
	at com.intellij.ui.treeStructure.treetable.TreeTable.updateUI(TreeTable.java:170)
	at com.intellij.util.IJSwingUtilities.updateComponentTreeUI(IJSwingUtilities.java:95)
	at com.intellij.ide.ui.laf.LafManagerImplKt.updateUI(LafManagerImpl.kt:1575)
	at com.intellij.ide.ui.laf.LafManagerImplKt.access$updateUI(LafManagerImpl.kt:1)
	at com.intellij.ide.ui.laf.LafManagerImpl.updateUI(LafManagerImpl.kt:902)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$EditorColorSchemeProcessor.handleCurrentSchemeSwitched(EditorColorsManagerImpl.java:193)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl$EditorColorSchemeProcessor.lambda$onCurrentSchemeSwitched$0(EditorColorsManagerImpl.java:187)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by marcelkliemannel** [comment]
Fixed.
